---
name: trivy-cache-db

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"      

jobs:
  trivy:
    name: Run trivy scanner
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Trivy Cache
        uses: ConsenSys/github-actions/trivy-update-cache@main
